
version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - APP_URL=${APP_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: ./.env
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
